// <auto-generated />
namespace TesteMixFiscal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IniciandoTesteMixFiscal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniciandoTesteMixFiscal));
        
        string IMigrationMetadata.Id
        {
            get { return "202011120139218_IniciandoTesteMixFiscal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
